### ISSUE TITLE
compiled binary files

### ISSUE THREAD

**Issue by flystar233** [compbiocore/VariantVisualization.jl#41]
Can you provide compiled binary files? It's too difficult for Julia to install and use packages

**Comment by gtollefson** [comment]
@flystar233 Unfortunately, we are not currently able to offer compiled binary files containing an executable version of VIVA. However, we are working on this for a future release. 

What part of the Julia language installation or package installation are you having trouble with? I would be happy to work with you to get Julia and our package installed so that you can use our VCF visualization tool, VIVA. 

Join the Julia Slack community and send me a direct message. My Slack username is *gtollefson*. You can join the Julia Slack channel following instructions here: https://discourse.julialang.org/t/announcing-a-julia-slack/4866






Once you download Julia, 

I am happy to

**Comment by flystar233** [comment]
There are so many dependency packages that I don't think it's all useful. The packages of julia still have too many deadly bugs in the repair process, such as building and network connections. Using R or Python might be a wise choice

**Comment by gtollefson** [comment]
@flystar233 Can you tell me specifically what your errors are? 

Our dependency builds are all passing and we perform cross platform testing on macOS, Windows, and Linux operating systems. 

Please tell me what operating system and Julia version you are using. Additionally, tell me if you are installing Julia packages on a shared network or on a remote server. Please post the complete error messages that you receive when trying to install VariantVisualization.jl and when building any broken dependencies. 

We carefully chose to build VIVA using Julia language, rather than Python or R, for a variety of reasons including its power, efficiency, and growing popularity in data science and biology research. You can read more about why we chose to use Julia by reading our preprint here: https://www.biorxiv.org/content/10.1101/589879v1

**Comment by flystar233** [comment]
Thank you for your patience. My operating system is Win10 and Julia version is 1.0.3 (I tried version 1.1.0 too). There are several mistakes:
`Pkg.build("Rsvg")`
`building LibCURL`
LibCURL wanted to download some packages according to bulid.jl, but there was no response. I chacked the bulid.jl, and manually downloaded these packages. I have no idea that why does this happen and where should these packages be put?
`building WinRPM` was also no response.

**Comment by gtollefson** [comment]
@flystar233 I’m happy to help and very glad you are interested in using our tool 😊. 

I’m confused by your description of the error messages. Can you copy and paste the complete error messages from your command line output?

Please include all error messages you receive when you:
1) clone VariantVisualization.jl 
and 
2) build any broken packages

**Comment by flystar233** [comment]
![111](https://user-images.githubusercontent.com/20431495/55454468-a0483e80-5612-11e9-874b-d9438c677b3f.png)
I can't download the files required by LibCURL, which may be due to some reasons. I can't solve this problem. Can you give me the entire folder of LibCURL and WinRPM? I'd like to replace my files with them and try again.

**Comment by gtollefson** [comment]
@flystar233 It looks like an issue with BinaryProvider. Here's a similar error, for a different package. The fix at the bottom of the page may help fix this issue when you show it to the LibCURL.jl developers. https://github.com/JuliaOpt/Clp.jl/issues/38

Rsvg builds (along with LibCURL and WinRPM) on Windows 10 64bit for me. This may be a 32 bit issue.

I would post this error message as an issue to the LibCurl.jl issues page (https://github.com/JuliaWeb/LibCURL.jl/issues) and reference this issue (https://github.com/JuliaOpt/Clp.jl/issues/38). I would also post the same error message on the WinRPM issues page.

**Comment by gtollefson** [comment]
@flystar233 Were you able to set up and use VIVA?

**Comment by gtollefson** [comment]
@flystar233 I'm going to close this, but please feel free to ask any questions here in the future.

**Comment by gtollefson** [comment]
@flystar233 We've developed a Docker container to run VIVA. This way, you won't have to install Julia or Julia package dependencies to run the tool. You just need to install Docker - check out our new [installation docs ](https://compbiocore.github.io/VariantVisualization.jl/latest/installation/#running-viva-with-docker-or-docker-compose)
